name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

permissions:
  contents: read   # Required to clone the repository
  packages: write  # Required to push to GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3  # This checks out the repository

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}  # Make sure you've added this secret

      # Step 3: Build Docker Image with lowercase repo name
      - name: Build Docker Image
        run: |
          IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]'):latest"
          echo "Building image with tag: $IMAGE_TAG"
          docker build -t $IMAGE_TAG .
        
      # Step 4: Push Docker Image to GHCR
      - name: Push Docker Image to GHCR
        run: |
          IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]'):latest"
          echo "Pushing image: $IMAGE_TAG"
          docker push $IMAGE_TAG

      # Step 5: Clean up Docker images
      - name: Clean up Docker images
        run: docker system prune -f  # Optional: cleans up unused Docker images
